<div class="row-fluid">
        <div class="span12">
          <section class="okapi-widget">
          <div class="okapi-widget-title"><img src="<?php echo $this->baseUrl();?>img/icons/help.png" class="okapi-widget-icon"><span>Help &amp; FAQs</span></div>
          <div class="okapi-widget-content">
            <p>updating...</p>
           <div style="text-align:center;"> <img src="<?php echo $this->baseUrl();?>img/icons2/help2.png" width="100" />
           <img src="<?php echo $this->baseUrl();?>img/login-page-logo.png" />
           </div>
          </div>
          </section>
        </div>
        
      </div>