   </div>
   <p class="pull-left" style="margin-left:10px; margin-top:-10px;"><small>Okapi Beta version | &copy; 2014</small></p>
</div>
<!-- overlayed element -->
<div class="apple_overlay" id="overlay">
  <!-- the external content is loaded inside this tag -->
  <div class="contentWrap"><div style="text-align:center;"><img src="<?php echo $this->baseUrl();?>img/loading.gif" /></div></div>
</div> 
<script type="text/javascript" src="<?php echo $this->baseUrl();?>js/jquery.hoverIntent.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>js/jquery.datatable.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>js/tables.js"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl();?>js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>js/header.js?v1"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>js/sidebar.js"></script> 
  
<script> 
   jQuery(function() { 
    // if the function argument is given to overlay,
    // it is assumed to be the onBeforeLoad event listener
    jQuery("a[rel]").overlay({
        mask: '#1D72A3',
        effect: 'apple',
        onBeforeLoad: function() {
            // grab wrapper element inside content
            var wrap = this.getOverlay().find(".contentWrap");
            // load the page specified in the trigger
            wrap.load(this.getTrigger().attr("href"));
        }
    });
});
	
</script>
<script>
 $(document).ready(function(){ 
	
	$(document).bind("contextmenu",function(e){
       // e.preventDefault();
    });
	sh(); 
	
	
	
});
function sh(){
	var shVal = window.screen.availHeight - 150; 
	document.getElementById('fc').style.height = shVal +'px';
	}
</script>
</body>
</html>