<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Okapi Project Preview System</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Okapi Project Previewing System">
<meta name="copyright" content="Copyright (c) 2014 Nathaniel Ashiagbor" />
<meta name="author" content="Nathaniel Ashiagbor">
<meta name="robots" content="noindex,nofollow" /> 
<link class="theme-css" href="<?php echo $this->baseUrl();?>css/okapi-white.css?v7" rel="stylesheet"> 
<link href="<?php echo $this->baseUrl();?>css/okapi-responsive.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl();?>css/ui-lightness/jquery-ui.css" rel="stylesheet" type="text/css">
<link href="<?php echo $this->baseUrl();?>css/gallery/modal.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl();?>css/validationEngine.jquery.css" rel="stylesheet" type="text/css"> 
<link href="<?php echo $this->baseUrl();?>css/ie.css" rel="stylesheet"/>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>js/jquery.min.js"></script> 

<script type="text/javascript" src="<?php echo $this->baseUrl();?>js/jquery.tools.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>js/okapi.js"></script>
<!--[if IE 8]><link href="<?php echo $this->baseUrl();?>css/ie8.css" rel="stylesheet"><![endif]--><!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]--><!--[if gte IE 9]><style type="text/css">.gradient{filter:none}</style><![endif]-->
 
</head>