<?php $acUser = new Zend_Session_Namespace(); ?>
<div class="row-fluid">
<div class="span12">
          <section class="okapi-widget">
          <div class="okapi-widget-title"><img src="<?php echo $this->baseUrl();?>img/icons/notepad.png" class="okapi-widget-icon"><span>Your Projects Available For Preview</span></div>
          <div class="okapi-widget-content">
          <?php if(count($this->projectList) > 0){ ?>
            <table class="table table-striped table-bordered">
              
              <thead>
                <tr>
                  <th>Project Title</th> 
                  <th>Uploaded On</th>
                  <th>Last Updated</th>
                  <th width="10%">Options</th>
                </tr>
              </thead>
              <tbody>
              <?php
			  if($acUser->level == 'admin'){
			  foreach($this->projectList as $pl){ ?>
                <tr>
                  <td><a href="<?php echo $this->baseUrl()."preview/project/v/".$pl->id;?>"><?php echo $pl->projectName;?></a></td> 
                  <td style="font-size:9px;"><?php echo $this->dateFormat($pl->dateCreated);?></td>
                  <td style="font-size:9px;">
                  <?php 
				  $stat = @stat('../projects/'.$pl->folderName);
				  echo $this->dateFormat($stat['mtime']);
				  ?>
                  </td>
                  <td>
                  <a href="<?php echo $this->baseUrl();?>preview/project/v/<?php echo $pl->id;?>" class="edit"><img src="<?php echo $this->baseUrl();?>img/icons/play.png" title="Preview" alt="View"></a>
                
                  </td>
                </tr> 
                
                <?php }
			  }else {
				  $pInfo = new Application_Model_DbTable_Projects;
				  foreach($this->projectList as $cpl){
				  	$pl = $pInfo->getById($cpl->project_ID);
					?>
                <tr>
                  <td><a href="<?php echo $this->baseUrl()."preview/project/v/".$pl->id;?>"><?php echo $pl->projectName;?></a></td> 
                  <td style="font-size:9px;"><?php echo $this->dateFormat($pl->dateCreated);?></td>
                  <td style="font-size:9px;">
                  <?php 
				  //$stat = @stat('../projects/'.$pl->folderName);
				  echo $this->dateFormat(@$this->lastMod('../projects/'.$pl->folderName)); 
				  ?>
                  </td>
                  <td>
                  <a href="<?php echo $this->baseUrl();?>preview/project/v/<?php echo $pl->id;?>" class="edit"><img src="<?php echo $this->baseUrl();?>img/icons/play.png" title="Preview" alt="View"></a>
                
                  </td>
                </tr> 
                
                <?php 
					}
				  }
			  
				 ?>
              </tbody>
               
            </table>
            
            
            <?php
            }else{
				  ?>
                  
                  <div class="alert alert-info"><a class="close" data-dismiss="alert" href="#">×</a><img src="<?php echo $this->baseUrl();?>img/icons2/info.png" width="20" /> &nbsp;
<strong>Sorry, no projects attached to your email address yet. </strong> </div>
                  <?php
				  }
            
             ?>
            
            
            
            
          </div>
          </section>
        </div>
        </div>